disableUpdater: false
first-login:
  hits: 20
  seconds: 1200
confirmation:
  enabled: false
  delay: 30
nickColor: 'DARK_PURPLE'
commandListEnabled: true
commandListDenylist: false
commandList:
  - immortallogin
  - immortal
  - im
  - help
  - rules
  - motd
