name: ImmortalLogin
author: timbeu31
description: Temporary god mode for new players
main: de.dustplanet.immortallogin.ImmortalLogin
version: ${project.version}${build.number}
website: https://www.spigotmc.org/resources/25481
api-version: 1.18
commands:
  immortallogin:
    description: Removes GodMode
    usage: /im
    aliases: [im, immortal]
permissions:
  immortallogin.*:
    description: Gives access to all ImmortalLogin permissions
    children:
      immortallogin.list.gods: true
  immortallogin.list.gods:
    description: Allows you to see the list of players in god mode
    default: op
softdepend: [NickNamer]
