name: ImmortalLogin
author: xGhOsTkiLLeRx
description: Temporary god mode for new players
main: de.dustplanet.immortallogin.ImmortalLogin
version: ${project.version}${build.number}
url: https://www.spigotmc.org/resources/25481
commands:
  immortallogin:
    description: Removes GodMode
    usage: /im
    aliases: [im, immortal]
softdepend: [NickNamer]
